name: Deploy to Heroku
on:
  push:
    branches:
      - master

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
  USERNAME: ${{ secrets.HEROKU_USERNAME }}

jobs:
  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Docker build
        working-directory: ./stack_db_api
        run: docker login --username=$USERNAME --password=$HEROKU_API_KEY registry.heroku.com

      - name: Publish
        working-directory: ./stack_db_api
        run: |
          docker build -t registry.heroku.com/$APP_NAME/web -f Dockerfile.prod .
          docker push registry.heroku.com/$APP_NAME/web
          heroku container:release web -a $APP_NAME
          heroku run bin/rails db:migrate RAILS_ENV=production -a $APP_NAME
